### ISSUE TITLE
failed to verify UbidotsSaveMultiValues

### ISSUE THREAD

**Issue by nugrahadi** [ubidots/ubidots-esp8266-serial#1]
failed to verify the UbidotsSaveMultiValues from example with this error messages :
`Build options changed, rebuilding all
UbidotsSaveMultiValues.ino:1:29: fatal error: UbidotsWizFi250.h: No such file or directory
compilation terminated.
Error compiling.`

**Comment by Metavix** [comment]
@nugrahadi  You are right thank you for your report, we will fix that as soon as possible
