### ISSUE TITLE
init#ONLINE?#final replies "Wrong command. Verify the command and send it again."

### ISSUE THREAD

**Issue by NelsGit** [ubidots/ubidots-esp8266-serial#11]
Hello. I get the error message above after sending the example test command. Help please.

**Comment by jotathebest** [comment]
I have just tested the example labeled as 'Arduino_Logger' and it works properly at my side:

![imagen](https://user-images.githubusercontent.com/5313567/36123345-57a627d0-101a-11e8-89de-7f1d14a50cf1.png)

please make sure that you are connecting properly your Rx and Tx arduino's pins with the ESP8266 serial pins.

Closing as this is not an issue.
