### ISSUE TITLE
error: espcomm_upload_mem failed

### ISSUE THREAD

**Issue by nishabe** [ubidots/ubidots-esp8266-serial#9]
Hello Team,
I am trying to set up a IOT assisted weather system using the following components in hand.
1) ArduinoUno 2) DHT22 3) ESP8266 (ESP 01)
I am trying to follow the steps provided in:
https://github.com/ubidots/ubidots-esp8266-serial
Below are my questions:
1) Do I have the right components? The steps mentions about Arduino MEGA and UartSBee or any Uart to USB device, which I do not have at present. Should I need both of them to proceed?
2) As of now I get error: espcomm_upload_mem failed, when I try to execute the steps.
3) In case I am already equipped, is there any significance in the 'Programmer:' selection?
Appreciate your help.

Below are the screenshots:
<img width="488" alt="12" src="https://user-images.githubusercontent.com/5227686/34459886-5af5c2fc-edc3-11e7-94b8-dde0032f2182.png">
<img width="319" alt="13" src="https://user-images.githubusercontent.com/5227686/34459887-5b0242ca-edc3-11e7-9605-b3d98025a677.png">
<img width="993" alt="11" src="https://user-images.githubusercontent.com/5227686/34459888-5b0e9a52-edc3-11e7-9168-18afbb201e79.png">

**Comment by jotathebest** [comment]
Hi there, answering your questions:

- ** Do I have the right components? The steps mentions about Arduino MEGA and UartSBee or any Uart to USB device, which I do not have at present. Should I need both of them to proceed? **

You can upload your firmware using the Arduino Mega in ICSP mode, but I advise you to use an UartSbee.

- **As of now I get error: espcomm_upload_mem failed, when I try to execute the steps **

Unfortunately, this error is related to the ESP8266 itself, not ours. The links below may serve you to make debugs on your side:

   - https://github.com/esp8266/Arduino/issues/2751
   - http://community.ubidots.com/t/solved-resolved-error-espcomm-upload-mem-failed/479

- ** In case I am already equipped, is there any significance in the 'Programmer:' selection? **

I have made the tests of the library using the first programmer, any tests using the second one have not been done.

As this is not an issue of the library, I proceed to close this thread.

Have a nice rest of day, if you need additional assistance feel free to write to our community: http://community.ubidots.com/

Have a nice rest of day
